apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: locumview
    labels:
        app.kubernetes.io/part-of: locumview
    annotations:
        locumview.org/tunnel-id: aca123d0-9281-427e-abdd-5d88696e14c6
        locumview.org/purpose: Cloudflare Tunnel connector token for the locumview tunnel (ADR 0004).
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:t6D8/XVlcISqDw/kDe63ZXuoMABxQr1B9UY/FZV84ZbAVnTj5cffNKmM8iNwut4OLyxnpx7zWQkkmOLAALtodJWQSM3LC2q/jlvthnD4wlRnYxXgr+OUNzXjkYoS0oI7aeUXOC02GKBZfZ70bZEhRNahQduHoCgkGL0iooCBmP/5uc1hVzGZ48JwzUUv06VQrnxAZeUj3Ec0nTnnrTuAD43oc0rbQVgyz6AZmgc+xArjo/8b1q/CHg==,iv:LLasaxiYoinkWHoZHB+Pa3r6jfwKfG+BiSVHg7RPx8Q=,tag:GPHUpVuUm41GVsyViiYMRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVjViYjFKaXBwWkFDMmxY
            R2ZrRzI5VzZJSkJOMExQQVZnMGRiYVhIK0R3CkhCSTh2MlZ5VmloTUJNN3paQ01F
            RzQ1UlNyU0FERVpCSkVkT2FJY0ZJWlkKLS0tIE1nS1BMZkhET2MySzlMRFQxT1hF
            UFVIcEJIVERFck1SRkF1MmE5Z3pkRFkK0G1Qhv2atgfpiLjXzCTZMO2zqdHsomOB
            nPpmfoAClw6xO0rO1VpnfDdVukiDUkN1WOtAzJZMA6uYYIjLE7s8kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtd08pu892une8jknwex6ey2rxdp76j3w67gstrd5vpvep24ussscpr59n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T00:48:11Z"
    mac: ENC[AES256_GCM,data:NxmjqSegjTVQ4ewvRjMlo6x0s1E27JVYH5nnM7tUvbCvK418kk6hcPihGgoFqvku8MuKFCGCujzBlbYmzECnWBQUSNqqlBCfB3Kt+wtIJ1PxQSTw22GxqPoldC+B8xnF08MdzTp7MVt45XMth0Jz+Fx9xn7yDFrIkNXkXssQcEk=,iv:5LcH6gRrD9vEQEib59Kekx3prt/qcy+SF+JYdZnkjQs=,tag:Qh4bYAM9YWtNpwPZcmirhA==,type:str]
    version: 3.13.3
