apiVersion: v1
kind: Secret
metadata:
    name: desktop-locumview-ref-dev-demo
    namespace: locumview
    labels:
        app.kubernetes.io/part-of: locumview
    annotations:
        locumview.org/purpose: GRD user-mode RDP login for the demo user on locumview-ref-dev, port 3391. Used by guacd only.
type: Opaque
stringData:
    hostname: ENC[AES256_GCM,data:wKHF/ogjkgnaeP6P,iv:JrUYQpToPNyFpgQsxmALw6G5g0xKMcqWzJr6Scqt5MM=,tag:TLOntfvaDa34rA4x2eLqeg==,type:str]
    port: ENC[AES256_GCM,data:CqyghA==,iv:ijEUyl+fUzvV/Lhmogk5Q7WwtxHx25tat3hLv/yjGko=,tag:1feuK74SI3SHKWVrZdcjOw==,type:str]
    rdp-username: ENC[AES256_GCM,data:6I5IUy1jR2yEcwOt,iv:sZOA92acS6KB5zPJN4PJv3mu3XjLaGiOoAY7yIKsmI8=,tag:hZpdBxQDkC/2BfwBCpzOhQ==,type:str]
    rdp-password: ENC[AES256_GCM,data:bAV9jTt+KCW4mWGUTazoCpnR+zZjA6qXvQvGuDu3GDY=,iv:Bd60bQHfz4/Wn6F0ZKP6/MusL30lYpEanNXRvUN3Dno=,tag:71i4TDxxjPw0zjLeMvVA4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTm1IVXdMT01xUVVxcVNj
            UU0rTHFwSFpYNmE5elROcWVHTy80ZmpuYVNZCm5GM1VwbzE0NmNXdmEwM0NkZ205
            cUlSbzRDRThKbm16UEdTbHM1d0FvM0UKLS0tIGpIcWh1S0l6bGd4dW9jSVYzekU5
            WXJsaXdrS3RLUzBpSDVSWTA2ek9kV28KfVlLTia3ZBBe8PncyeF22Le7Yyzm6yDZ
            0DoBHFiPip9x9OOfB2AxKc7gqsljJeOPctTU9IjvetptG9Zq0u/a/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtd08pu892une8jknwex6ey2rxdp76j3w67gstrd5vpvep24ussscpr59n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T01:22:19Z"
    mac: ENC[AES256_GCM,data:mMyC2Rx3CltW1P1tj3x/C+0xQHufBAUsUNtBq+9ZlohI89/mBpjhDewI1FgQ/oxh/xOd+Z6Dd5vALbIDgS3q0r+H1vNFECvJ6LW/rNoQtF8YVxq/9ZhUswUVQN+JdloU339pp/oVc03YkhXT0AD6SreEmlxDehjo3caaRnET5JI=,iv:YsBav0PNvUmsBzW9pciKMHfdtIWUjSIJKinTNKXg9mQ=,tag:YESyoiUIMma1b3D4gC0dEw==,type:str]
    version: 3.13.3
