apiVersion: v1
kind: Secret
metadata:
    name: desktop-locumview-ref-dev
    namespace: locumview
    labels:
        app.kubernetes.io/part-of: locumview
    annotations:
        locumview.org/purpose: GRD user-mode (headless) RDP login for locumview-ref-dev, port 3390. Used by guacd only.
type: Opaque
stringData:
    hostname: ENC[AES256_GCM,data:txT8nyI+EEurRCYf,iv:mNfe3CCZRqT6mO3sHuEHD5i2ROvBjwBu7c/C9LANNdY=,tag:Ij8RBy+TcUJN326+Xkx8NA==,type:str]
    port: ENC[AES256_GCM,data:jqoIiQ==,iv:nN5tB18eRqKvQFfKhguUD4XHhrPSDFjNMOYBPbu2vgs=,tag:h0XmMId7uSmbrLLpIyzeEA==,type:str]
    rdp-username: ENC[AES256_GCM,data:I0MUsvUKOEymMww=,iv:rIYdkQ9FP0nB4itjeBo/CdTFDdXC0NTfR6CNWWONS8g=,tag:3sah/LNerV4GI8///taEpQ==,type:str]
    rdp-password: ENC[AES256_GCM,data:G15FhzxG5QcdhAwzqeIIklmVyCJql7yopcUJ+AW4fhc=,iv:F0WfpGKJEvnSP+guv2MHtwxAqMTvLcVeLKtsgFdqDWk=,tag:OJspa8g5Xf6+S9TNxqD3zA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OXYwMncwcW5nTHE2c1hJ
            ejNnaXhyOEhrY0MzL3BhK0toK1Z4ZHg3NDI4CjI5VGJNYU9ZZHhxeXBsTG0yVW03
            cTJ1SGdlM09SSXVnMjk3ajVya0lUN28KLS0tIGgreEpsdW9ML1dhNkRSb0FEZWNM
            WjRGQTZHSFk4Y2diQ3hjQlBKbHdRSmcKFuW5gDgkEkMfAjDG/l+HUjXLMCELYiMM
            N7C3vQzcoPLyNkJAowfQSxTxzLQbrOLGKUbVYZVUgvxxBVqkQtB8FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtd08pu892une8jknwex6ey2rxdp76j3w67gstrd5vpvep24ussscpr59n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T17:19:36Z"
    mac: ENC[AES256_GCM,data:15FziKEwXz9C+R1Oi2SKc5ETh0AJelI5DJkq3Yq48kqXVGbv6C2MKe1CbT3jrlnaCZl9y6VR47cgStBuiSidXlkrl6MLI8ofTemke+KOrBmFlcSfBvmDQihPmsB5tw5dwxlx+JNrI5VTlLQ8bbrykTMXNlYHFfp4noMoA4WquGU=,iv:G3bUhMzohdaZTPUzmqtz7flD2UUlT3ckH0dGtE1OqmQ=,tag:l7O6ljpd+1wcAd1nVUO6Zw==,type:str]
    version: 3.13.3
