apiVersion: v1
kind: Secret
metadata:
    name: guacamole-db
    namespace: locumview
    labels:
        app.kubernetes.io/part-of: locumview
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:zHDbupFhGvjB0VYDgkMi1gKbCRbqkOgm+z5DfCo7L3U=,iv:uvjUnUkFTKmSev7wdHvZKxbRkBJZMCvy6S7HSgOAZZA=,tag:NxBJA6RLl2AS7Wzf6Qfx8Q==,type:str]
    app-password: ENC[AES256_GCM,data:l78ycryTVTdn6cfkLNjvILQmEZap+IwNpKRzNS28IEQ=,iv:RQwuj7DpsX/5PPqfYtzj7nI3zTG+FtJGhwkqV1M6k2w=,tag:3R847dZw0jhO3Bx+BZbq/Q==,type:str]
    admin-password: ENC[AES256_GCM,data:MJpgmWmwHFJf8fwRAKLNQ60DAMZ45FRn,iv:CYCvgswq4N6/8Tvofk6EWYEcQPMw5e7wskC5dPGjMu4=,tag:3gGYzaIYltSPNGYcGKSKbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYjdrdkpWdW11NURJUnZn
            dEI3L1lGUjV3NFlraGE5SlRSVjZxOURQcm1jClVWT3d0d3p5SG42R2lPQ3JmSmt4
            UEprWnlzYnloRE95dmZDRUt6SjQ1MVEKLS0tIEdnOTkrRU8ydnhKOFZGV1AwbHBX
            czJPenRFQ3Z5N2lZTlE0VmJ3YnA4cHcKo9J2MWp4y8A+ccvOTF4hijMGHSjJiHAy
            5KkxL7etNFZIn5eE0P5NfgA2/hZJtu5hTJzFfoKbr6w89EOe+s4D2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtd08pu892une8jknwex6ey2rxdp76j3w67gstrd5vpvep24ussscpr59n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:36:07Z"
    mac: ENC[AES256_GCM,data:4gsE5IMmnmxum5aWPuwgOY/mO9Mh3rrjnROOhRmgebajz+SB26k++noWNThdZT0ZzkqjtdenBcYNYfh4lqaANIfqCAQCR28EJKN5k9OEhQ0rG+v7l3SN6jvtWcb7AqnCoBMsfh9RoW987LT1xyrUg/466Fu4csTYrM7QcOVNsgQ=,iv:P+P+Pn7/VCz57ILjVcevcWTbSwAP4D/VRWvlTuZpAOc=,tag:RqLPx+PUbfOjTHPJn1CIcg==,type:str]
    version: 3.13.3
