apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: locumview
    labels:
        app.kubernetes.io/part-of: locumview
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Hl5w8RhSfPC2u0njurMhyN9BPVgfIcJDnT/ipc2oP+8=,iv:2NjQisFhY61mtOpOMtGY8quj3BlYNwVGM8SRfoqnwZs=,tag:CIKRbbx6pGk2ghfAerWQDA==,type:str]
    db-password: ENC[AES256_GCM,data:TWn6B5XO9LT3188qRSsrnNXMk6sJgt+TBr57d9v1ddI=,iv:QryGSeEKpYHDXfE3FZj/7Jl9TMGExxTP2YAjbWroAAo=,tag:2LRET5NhH9XHuxzWUA4o6Q==,type:str]
    bootstrap-admin-password: ENC[AES256_GCM,data:yN4Br1bkJPbIZC2KHVETPCg8czsqr/hr2fB3tg/avQc=,iv:W4Jv3uN0AMbeNMbgoFvNm7xiQq1oL/d7S+A7xeMM0lI=,tag:RAiKrEf0wNlVHMu3Mqu5IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcnc2WWNmUDFQc1hGSEE1
            Y2h6SDg4bHhQZGV4elZGN29yVGJObDM5SW1jCktSWFZPWko2OStOby9kU0s5bnA5
            am1lRGVFOWFUWlhnajMyUFNaSk10bncKLS0tIHJ6bVNKMWgwbm9pVXJMN3ZIODdm
            ZDBiV21qR01RbFppenI1WGtQZHdaWlkKUY9MAyiVvd+xmOWAnNobhd67Up39RBVB
            9U6Qx2rEKlg493s/X+/xeHkVPfSteYaWkBkkX/WbP/xkygdXiPn8Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtd08pu892une8jknwex6ey2rxdp76j3w67gstrd5vpvep24ussscpr59n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:57:41Z"
    mac: ENC[AES256_GCM,data:beW7wFlM4FoW5jd5WMKaBXEJZOKHCeMZSydOGaqPQN7b8GqvddHONgsGTwfUBAkc1iPr7hmNzrdWPk4zEfN+gQdWsGt20DZijALnX7+kFz7sZ3xdhAHaH7NT0HfJmeoJ0/e6hkvtuRLp3f5CXbfKgiDCry5z9aYVIHq4bMZiNGM=,iv:HK1UNZFlDzcenYAHbayS15AXsmKud6v8ZylGl0d+hjA=,tag:yJy52MOSmg21dtpdgHTSlw==,type:str]
    version: 3.13.3
